/* Prompt Studio data — autocomplete vocabulary, one-tap modifiers, and a
   hand-tuned gold cache of the top real-world LLM queries (researched across
   ChatGPT/Gemini/Claude/Perplexity usage patterns; each prompt pre-reasoned
   for succinct output and served instantly on similarity match). */

window.PS_MODS = [
 {
  "id": "table",
  "label": "Table",
  "text": "Format as a compact table."
 },
 {
  "id": "bul3",
  "label": "3 bullets",
  "text": "Answer in 3 bullets max."
 },
 {
  "id": "steps",
  "label": "Steps",
  "text": "Numbered steps only, one line each.",
  "doms": [
   "tech",
   "home",
   "cook",
   "plan",
   "debug",
   "fit"
  ]
 },
 {
  "id": "eli5",
  "label": "ELI5",
  "text": "Explain like I'm five, 3 sentences.",
  "doms": [
   "learn",
   "sci",
   "math"
  ]
 },
 {
  "id": "example",
  "label": "Real example",
  "text": "Give one concrete real-world example.",
  "doms": [
   "learn",
   "biz",
   "market",
   "lang"
  ]
 },
 {
  "id": "diagram",
  "label": "Diagram",
  "text": "Include a simple text diagram.",
  "doms": [
   "learn",
   "sci",
   "math",
   "tech",
   "code"
  ]
 },
 {
  "id": "proscons",
  "label": "Pros/cons",
  "text": "3 pros, 3 cons, nothing else.",
  "doms": [
   "decide",
   "shop",
   "biz"
  ]
 },
 {
  "id": "w100",
  "label": "100 words",
  "text": "Under 100 words total."
 },
 {
  "id": "checklist",
  "label": "Checklist",
  "text": "Format as an ordered checklist.",
  "doms": [
   "plan",
   "travel",
   "home",
   "career"
  ]
 },
 {
  "id": "analogy",
  "label": "Analogy",
  "text": "Include one short analogy.",
  "doms": [
   "learn",
   "sci"
  ]
 },
 {
  "id": "quiz",
  "label": "Quiz me",
  "text": "Then quiz me with 3 short questions.",
  "doms": [
   "learn",
   "lang",
   "math",
   "sci"
  ]
 },
 {
  "id": "next",
  "label": "Next step",
  "text": "End with one concrete next step.",
  "doms": [
   "career",
   "biz",
   "plan",
   "money",
   "fit"
  ]
 },
 {
  "id": "yesno",
  "label": "Yes/no",
  "text": "Start with yes or no, then why.",
  "doms": [
   "decide",
   "health",
   "money"
  ]
 },
 {
  "id": "top3",
  "label": "Top 3",
  "text": "Just the top 3, ranked.",
  "doms": [
   "shop",
   "create",
   "fun"
  ]
 },
 {
  "id": "compare",
  "label": "Compare",
  "text": "Compare in a two-column table.",
  "doms": [
   "decide",
   "shop",
   "tech"
  ]
 },
 {
  "id": "mistakes",
  "label": "Mistakes",
  "text": "List the 3 most common mistakes.",
  "doms": [
   "learn",
   "fit",
   "cook",
   "money",
   "career"
  ]
 },
 {
  "id": "numbers",
  "label": "Numbers",
  "text": "Include specific numbers and figures.",
  "doms": [
   "money",
   "biz",
   "analyze",
   "fit",
   "sci"
  ]
 },
 {
  "id": "sources",
  "label": "Sources",
  "text": "Cite 2\u20133 reputable sources.",
  "doms": [
   "health",
   "sci",
   "money",
   "legal"
  ]
 },
 {
  "id": "template",
  "label": "Template",
  "text": "Give a fill-in-the-blank template.",
  "doms": [
   "write",
   "email",
   "biz",
   "legal"
  ]
 },
 {
  "id": "codeonly",
  "label": "Code only",
  "text": "Code only, no explanation.",
  "doms": [
   "code",
   "debug"
  ]
 },
 {
  "id": "mermaid",
  "label": "Mermaid",
  "text": "Output a mermaid diagram only.",
  "doms": [
   "code",
   "agent",
   "tech"
  ]
 },
 {
  "id": "cheat",
  "label": "Cheat sheet",
  "text": "Format as a one-screen cheat sheet.",
  "doms": [
   "learn",
   "lang",
   "math",
   "code"
  ]
 },
 {
  "id": "counter",
  "label": "Counter",
  "text": "Add one strong counterargument.",
  "doms": [
   "decide",
   "analyze",
   "biz"
  ]
 },
 {
  "id": "askfirst",
  "label": "Ask first",
  "text": "Ask one clarifying question before answering.",
  "doms": [
   "agent",
   "debug",
   "decide",
   "legal"
  ]
 },
 {
  "id": "blunt",
  "label": "Blunt",
  "text": "Be blunt; no hedging or caveats."
 },
 {
  "id": "casual",
  "label": "Casual",
  "text": "Casual, conversational tone.",
  "doms": [
   "write",
   "email",
   "social",
   "fun"
  ]
 },
 {
  "id": "formal",
  "label": "Formal",
  "text": "Formal, professional tone.",
  "doms": [
   "write",
   "email",
   "career",
   "legal"
  ]
 },
 {
  "id": "deeper",
  "label": "Deeper",
  "text": "Go one level deeper, still brief."
 },
 {
  "id": "planfirst",
  "label": "Plan first",
  "text": "Plan first; wait for my OK before executing.",
  "doms": [
   "agent",
   "code",
   "biz"
  ]
 },
 {
  "id": "definedone",
  "label": "Define done",
  "text": "Define done as a checkable end state first.",
  "doms": [
   "agent",
   "code",
   "biz"
  ]
 },
 {
  "id": "showproof",
  "label": "Show proof",
  "text": "Show evidence: paste the output that proves success.",
  "doms": [
   "agent",
   "code",
   "debug"
  ]
 },
 {
  "id": "scopeguard",
  "label": "Scope guard",
  "text": "Fix only what's asked; note other issues, don't touch.",
  "doms": [
   "agent",
   "code",
   "debug"
  ]
 },
 {
  "id": "escalate",
  "label": "Escalate",
  "text": "If blocked twice on one thing, stop and ask.",
  "doms": [
   "agent"
  ]
 },
 {
  "id": "cleanup",
  "label": "Clean up",
  "text": "Remove temp files, branches, debug code before finishing.",
  "doms": [
   "agent",
   "code"
  ]
 }
];

window.PS_VOCAB = [
{"t":"invest 10k","d":"money"},
{"t":"xbox vs ps5","d":"fun"},
{"t":"ev vs hybrid","d":"decide"},
{"t":"fix my resume","d":"career"},
{"t":"run faster 5k","d":"fit"},
{"t":"fix cors error","d":"debug"},
{"t":"sql join types","d":"code"},
{"t":"open a roth ira","d":"money"},
{"t":"outline a novel","d":"write"},
{"t":"quit sugar plan","d":"health"},
{"t":"stoicism basics","d":"learn"},
{"t":"undo git rebase","d":"code"},
{"t":"couch to 5k plan","d":"fit"},
{"t":"css center a div","d":"code"},
{"t":"date night ideas","d":"fun"},
{"t":"date night spots","d":"local"},
{"t":"gut health foods","d":"health"},
{"t":"next js vs react","d":"code"},
{"t":"vitamin d dosage","d":"health"},
{"t":"youtube seo tips","d":"market"},
{"t":"best brunch spots","d":"local"},
{"t":"chatgpt vs claude","d":"tech"},
{"t":"cheap eats nearby","d":"local"},
{"t":"jump rope workout","d":"fit"},
{"t":"keep my prs green","d":"agent"},
{"t":"organize my inbox","d":"agent"},
{"t":"side hustle ideas","d":"biz"},
{"t":"vpn do i need one","d":"tech"},
{"t":"adopt a dog or cat","d":"decide"},
{"t":"apartment vs house","d":"decide"},
{"t":"avoid jet lag tips","d":"travel"},
{"t":"cheap dinner ideas","d":"cook"},
{"t":"duolingo vs babbel","d":"lang"},
{"t":"fix a leaky faucet","d":"home"},
{"t":"haiku about autumn","d":"create"},
{"t":"job interview prep","d":"career"},
{"t":"live music tonight","d":"local"},
{"t":"merge conflict fix","d":"debug"},
{"t":"pitch deck outline","d":"biz"},
{"t":"tiktok video ideas","d":"social"},
{"t":"yoga for back pain","d":"fit"},
{"t":"baby sleep schedule","d":"parent"},
{"t":"bread without yeast","d":"cook"},
{"t":"career change at 40","d":"career"},
{"t":"instagram bio ideas","d":"social"},
{"t":"keto dinner recipes","d":"cook"},
{"t":"math help fractions","d":"math"},
{"t":"nda template simple","d":"legal"},
{"t":"raise test coverage","d":"agent"},
{"t":"restaurants near me","d":"local"},
{"t":"stock vs index fund","d":"money"},
{"t":"things to do nearby","d":"local"},
{"t":"toddler won't sleep","d":"parent"},
{"t":"why is the sky blue","d":"sci"},
{"t":"world war 2 summary","d":"learn"},
{"t":"zoloft side effects","d":"health"},
{"t":"zoom interview tips","d":"career"},
{"t":"5 year plan examples","d":"plan"},
{"t":"apy vs interest rate","d":"money"},
{"t":"budget for a wedding","d":"money"},
{"t":"build muscle at home","d":"fit"},
{"t":"crypto for beginners","d":"money"},
{"t":"easy meal prep ideas","d":"cook"},
{"t":"etsy shop name ideas","d":"biz"},
{"t":"git undo last commit","d":"code"},
{"t":"grad school worth it","d":"decide"},
{"t":"heat pump vs furnace","d":"home"},
{"t":"hidden gems to visit","d":"local"},
{"t":"kubernetes vs docker","d":"tech"},
{"t":"learn to type faster","d":"learn"},
{"t":"migraine relief fast","d":"health"},
{"t":"passive income ideas","d":"money"},
{"t":"quick dinner for two","d":"cook"},
{"t":"quiet a squeaky door","d":"home"},
{"t":"riddles with answers","d":"fun"},
{"t":"scenic drives nearby","d":"local"},
{"t":"time blocking method","d":"plan"},
{"t":"tone down this email","d":"write"},
{"t":"trip to japan 7 days","d":"travel"},
{"t":"zero-based budgeting","d":"money"},
{"t":"analyze this csv data","d":"analyze"},
{"t":"ankle sprain recovery","d":"health"},
{"t":"build a data pipeline","d":"agent"},
{"t":"burnout warning signs","d":"health"},
{"t":"carry on packing tips","d":"travel"},
{"t":"clear cache on iphone","d":"tech"},
{"t":"dna vs rna difference","d":"sci"},
{"t":"docker compose basics","d":"tech"},
{"t":"fix all failing tests","d":"agent"},
{"t":"go to market strategy","d":"biz"},
{"t":"image for blog header","d":"image"},
{"t":"image prompt for logo","d":"image"},
{"t":"logo ideas for bakery","d":"image"},
{"t":"mac vs windows laptop","d":"decide"},
{"t":"mattress buying guide","d":"shop"},
{"t":"morning routine ideas","d":"plan"},
{"t":"nearest hiking trails","d":"local"},
{"t":"nyc weekend itinerary","d":"travel"},
{"t":"online business ideas","d":"biz"},
{"t":"organize small closet","d":"home"},
{"t":"out of office message","d":"email"},
{"t":"overnight oats recipe","d":"cook"},
{"t":"ozempic pros and cons","d":"health"},
{"t":"plan a surprise party","d":"plan"},
{"t":"roast chicken in oven","d":"cook"},
{"t":"set up ci for my repo","d":"agent"},
{"t":"sleep better at night","d":"health"},
{"t":"spanish for beginners","d":"lang"},
{"t":"study plan for finals","d":"plan"},
{"t":"wifi extender vs mesh","d":"tech"},
{"t":"xml to json converter","d":"code"},
{"t":"youtube channel ideas","d":"create"},
{"t":"agent to sort my inbox","d":"agent"},
{"t":"analyze survey results","d":"analyze"},
{"t":"anniversary gift ideas","d":"shop"},
{"t":"app crashes on startup","d":"debug"},
{"t":"ask for a raise script","d":"career"},
{"t":"automate email replies","d":"agent"},
{"t":"best exercises for abs","d":"fit"},
{"t":"board games for adults","d":"fun"},
{"t":"business plan template","d":"biz"},
{"t":"compare two job offers","d":"decide"},
{"t":"data cleaning in excel","d":"analyze"},
{"t":"dog won't stop barking","d":"home"},
{"t":"flight deals to europe","d":"travel"},
{"t":"german cases explained","d":"lang"},
{"t":"improve my wifi signal","d":"tech"},
{"t":"japanese for beginners","d":"lang"},
{"t":"kitchen remodel budget","d":"home"},
{"t":"knee pain when running","d":"fit"},
{"t":"knitting for beginners","d":"create"},
{"t":"meal prep for the week","d":"cook"},
{"t":"midjourney prompt tips","d":"image"},
{"t":"negotiate salary offer","d":"career"},
{"t":"rent vs buy calculator","d":"decide"},
{"t":"rest api design basics","d":"code"},
{"t":"restyle photo as anime","d":"image"},
{"t":"sick day email to boss","d":"email"},
{"t":"smart thermostat setup","d":"home"},
{"t":"standing desk worth it","d":"shop"},
{"t":"summarize this article","d":"summarize"},
{"t":"teenager attitude help","d":"parent"},
{"t":"valentine's gift ideas","d":"shop"},
{"t":"vlookup vs index match","d":"tech"},
{"t":"xbox parental controls","d":"parent"},
{"t":"xlsx to csv conversion","d":"tech"},
{"t":"yearly budget template","d":"money"},
{"t":"apology email to client","d":"email"},
{"t":"business plan one pager","d":"biz"},
{"t":"cold email to investors","d":"email"},
{"t":"conjugate ser and estar","d":"lang"},
{"t":"dating profile bio help","d":"social"},
{"t":"dinner party menu for 8","d":"cook"},
{"t":"dishwasher not draining","d":"home"},
{"t":"emergency fund how much","d":"money"},
{"t":"europe trip on a budget","d":"travel"},
{"t":"graduation speech ideas","d":"write"},
{"t":"healthy breakfast ideas","d":"cook"},
{"t":"ideas for team building","d":"biz"},
{"t":"japan 10 days with kids","d":"travel"},
{"t":"keywords for my website","d":"market"},
{"t":"kids screen time limits","d":"parent"},
{"t":"lose weight without gym","d":"fit"},
{"t":"memory leak in node app","d":"debug"},
{"t":"pandas group by example","d":"code"},
{"t":"podcast episode outline","d":"create"},
{"t":"poem for mom's birthday","d":"create"},
{"t":"security deposit rights","d":"legal"},
{"t":"server 500 error causes","d":"debug"},
{"t":"skills to learn in 2026","d":"career"},
{"t":"sourdough starter guide","d":"cook"},
{"t":"speeding ticket options","d":"legal"},
{"t":"split the bill with tip","d":"math"},
{"t":"summarize meeting notes","d":"summarize"},
{"t":"video editing apps free","d":"create"},
{"t":"x-ray results explained","d":"health"},
{"t":"yard drainage solutions","d":"home"},
{"t":"zapier automation ideas","d":"agent"},
{"t":"air fryer chicken recipe","d":"cook"},
{"t":"best time to visit italy","d":"travel"},
{"t":"climate change key facts","d":"sci"},
{"t":"college essay brainstorm","d":"write"},
{"t":"copyright for my artwork","d":"legal"},
{"t":"enhance old family photo","d":"image"},
{"t":"explain machine learning","d":"learn"},
{"t":"free things to do nearby","d":"local"},
{"t":"google ads for beginners","d":"market"},
{"t":"grow instagram followers","d":"market"},
{"t":"hangover cure that works","d":"health"},
{"t":"hobbies to try this year","d":"fun"},
{"t":"iphone or android switch","d":"decide"},
{"t":"iron deficiency symptoms","d":"health"},
{"t":"javascript array methods","d":"code"},
{"t":"meditation for beginners","d":"health"},
{"t":"mortgage rates explained","d":"money"},
{"t":"name ideas for a podcast","d":"create"},
{"t":"news summary of the week","d":"summarize"},
{"t":"paint colors for bedroom","d":"home"},
{"t":"pay off credit card debt","d":"money"},
{"t":"photosynthesis explained","d":"sci"},
{"t":"picky eater toddler tips","d":"parent"},
{"t":"potty training in 3 days","d":"parent"},
{"t":"python indentation error","d":"debug"},
{"t":"quarterly goals template","d":"plan"},
{"t":"seo basics for beginners","d":"market"},
{"t":"set up a deploy pipeline","d":"agent"},
{"t":"short story prompt ideas","d":"create"},
{"t":"solve quadratic equation","d":"math"},
{"t":"song lyrics about summer","d":"create"},
{"t":"speed reading techniques","d":"learn"},
{"t":"text back after ghosting","d":"social"},
{"t":"typescript vs javascript","d":"code"},
{"t":"unclog a drain naturally","d":"home"},
{"t":"validate a business idea","d":"biz"},
{"t":"watch my logs for errors","d":"agent"},
{"t":"weekend day trips nearby","d":"local"},
{"t":"weekend plans when bored","d":"fun"},
{"t":"weekly schedule template","d":"plan"},
{"t":"wine pairing with salmon","d":"cook"},
{"t":"wordpress vs squarespace","d":"tech"},
{"t":"zero waste swaps at home","d":"home"},
{"t":"algebra word problem help","d":"math"},
{"t":"anxiety coping techniques","d":"health"},
{"t":"automate my daily reports","d":"agent"},
{"t":"babysit this pull request","d":"agent"},
{"t":"backup my photos to cloud","d":"tech"},
{"t":"best coffee shops in town","d":"local"},
{"t":"best time to book flights","d":"travel"},
{"t":"down payment savings plan","d":"money"},
{"t":"excel formula for vlookup","d":"tech"},
{"t":"find trends in sales data","d":"analyze"},
{"t":"french phrases for travel","d":"lang"},
{"t":"gluten free dessert ideas","d":"cook"},
{"t":"grocery list for the week","d":"cook"},
{"t":"jazz albums for beginners","d":"fun"},
{"t":"learn python from scratch","d":"learn"},
{"t":"lease agreement red flags","d":"legal"},
{"t":"linkedin summary examples","d":"career"},
{"t":"network effects explained","d":"learn"},
{"t":"notion setup for students","d":"tech"},
{"t":"probability of dice rolls","d":"math"},
{"t":"protein intake calculator","d":"fit"},
{"t":"python list comprehension","d":"code"},
{"t":"react useeffect explained","d":"code"},
{"t":"remove mold from bathroom","d":"home"},
{"t":"retirement savings by age","d":"money"},
{"t":"thesis statement examples","d":"write"},
{"t":"tldr of this email thread","d":"summarize"},
{"t":"travel insurance worth it","d":"travel"},
{"t":"used car buying checklist","d":"shop"},
{"t":"will and testament basics","d":"legal"},
{"t":"write a mission statement","d":"biz"},
{"t":"zodiac sign compatibility","d":"fun"},
{"t":"decline a meeting politely","d":"email"},
{"t":"draft a resignation letter","d":"write"},
{"t":"interview questions to ask","d":"career"},
{"t":"itinerary for paris 3 days","d":"travel"},
{"t":"jealousy in a relationship","d":"social"},
{"t":"llc vs sole proprietorship","d":"biz"},
{"t":"make friends in a new city","d":"social"},
{"t":"monitor the deploy tonight","d":"agent"},
{"t":"privacy policy for website","d":"legal"},
{"t":"quotes for graduation card","d":"write"},
{"t":"regex for email validation","d":"code"},
{"t":"road trip route california","d":"travel"},
{"t":"science fair project ideas","d":"sci"},
{"t":"translate email to spanish","d":"lang"},
{"t":"update my linkedin profile","d":"career"},
{"t":"uti symptoms and treatment","d":"health"},
{"t":"vacation ideas for couples","d":"travel"},
{"t":"work from home setup ideas","d":"home"},
{"t":"workout plan 3 days a week","d":"fit"},
{"t":"yeast substitute in baking","d":"cook"},
{"t":"ai tools for small business","d":"biz"},
{"t":"bash script to rename files","d":"code"},
{"t":"build a chatbot for my site","d":"agent"},
{"t":"build and deploy my website","d":"agent"},
{"t":"caption ideas for instagram","d":"social"},
{"t":"compound interest explained","d":"money"},
{"t":"cover letter for internship","d":"career"},
{"t":"email to reschedule meeting","d":"email"},
{"t":"fantasy football team names","d":"fun"},
{"t":"first time home buyer steps","d":"home"},
{"t":"garden layout for beginners","d":"home"},
{"t":"guitar chords for beginners","d":"learn"},
{"t":"half marathon training plan","d":"fit"},
{"t":"history of the roman empire","d":"learn"},
{"t":"journal prompts for anxiety","d":"health"},
{"t":"key takeaways from this pdf","d":"summarize"},
{"t":"lasagna recipe from scratch","d":"cook"},
{"t":"packing list for beach trip","d":"travel"},
{"t":"percentage increase formula","d":"math"},
{"t":"refactor this legacy module","d":"agent"},
{"t":"running shoes for flat feet","d":"shop"},
{"t":"scrape prices from websites","d":"agent"},
{"t":"undefined is not a function","d":"debug"},
{"t":"upper body dumbbell workout","d":"fit"},
{"t":"x axis labels in matplotlib","d":"code"},
{"t":"yellow leaves on houseplant","d":"home"},
{"t":"zucchini recipes for dinner","d":"cook"},
{"t":"black holes explained simply","d":"sci"},
{"t":"blog post about productivity","d":"write"},
{"t":"chess openings for beginners","d":"learn"},
{"t":"clean up my downloads folder","d":"agent"},
{"t":"creatine benefits and dosage","d":"fit"},
{"t":"daily news digest automation","d":"agent"},
{"t":"debug null pointer exception","d":"debug"},
{"t":"house offer negotiation tips","d":"home"},
{"t":"interpret blood test results","d":"analyze"},
{"t":"make this sound professional","d":"write"},
{"t":"nap schedule for 6 month old","d":"parent"},
{"t":"newborn checklist essentials","d":"parent"},
{"t":"product market fit explained","d":"learn"},
{"t":"rolling r pronunciation tips","d":"lang"},
{"t":"small bathroom storage ideas","d":"home"},
{"t":"standard deviation explained","d":"math"},
{"t":"birthday party ideas for kids","d":"fun"},
{"t":"bullet points from transcript","d":"summarize"},
{"t":"customer retention strategies","d":"biz"},
{"t":"email subject lines that work","d":"market"},
{"t":"intermittent fasting schedule","d":"health"},
{"t":"remote work productivity tips","d":"career"},
{"t":"salary range for data analyst","d":"career"},
{"t":"sentiment analysis of reviews","d":"analyze"},
{"t":"spot errors in my spreadsheet","d":"analyze"},
{"t":"unit conversion cups to grams","d":"math"},
{"t":"vegetarian high protein meals","d":"cook"},
{"t":"childproof the house checklist","d":"parent"},
{"t":"directions and transit options","d":"local"},
{"t":"fever in toddler when to worry","d":"parent"},
{"t":"generate a birthday card image","d":"image"},
{"t":"kid friendly activities nearby","d":"local"},
{"t":"lower blood pressure naturally","d":"health"},
{"t":"networking email to a stranger","d":"email"},
{"t":"newsletter ideas for customers","d":"market"},
{"t":"nutrition plan for muscle gain","d":"fit"},
{"t":"questions to ask on first date","d":"social"},
{"t":"refinance my mortgage worth it","d":"money"},
{"t":"resume bullet points for sales","d":"career"},
{"t":"rewrite this paragraph clearly","d":"write"},
{"t":"tax deductions for freelancers","d":"money"},
{"t":"thank you note after interview","d":"email"},
{"t":"visa requirements for thailand","d":"travel"},
{"t":"wedding speech for best friend","d":"write"},
{"t":"essay outline on climate change","d":"write"},
{"t":"follow up email after interview","d":"email"},
{"t":"gift for dad who has everything","d":"shop"},
{"t":"hiring first employee checklist","d":"biz"},
{"t":"long distance relationship tips","d":"social"},
{"t":"migrate my database to postgres","d":"agent"},
{"t":"quiz questions for trivia night","d":"fun"},
{"t":"weekly meal plan family of four","d":"cook"},
{"t":"automate my weekly status report","d":"agent"},
{"t":"best noise cancelling headphones","d":"shop"},
{"t":"condense this report to one page","d":"summarize"},
{"t":"invoice template for freelancers","d":"biz"},
{"t":"product photo background removal","d":"image"},
{"t":"small talk conversation starters","d":"social"},
{"t":"watercolor style portrait prompt","d":"image"},
{"t":"character names for fantasy novel","d":"create"},
{"t":"product launch announcement ideas","d":"market"},
{"t":"recursion explained with examples","d":"learn"},
{"t":"onboarding checklist for new hires","d":"biz"},
{"t":"upgrade all my dependencies safely","d":"agent"},
{"t":"schedule social posts automatically","d":"agent"},
{"t":"stretching routine for desk workers","d":"fit"},
{"t":"business ideas with low startup cost","d":"biz"},
{"t":"movie recommendations like inception","d":"fun"}
];

window.PS_GOLD = [
{"q":"write an email","d":"email","p":"Draft the email in under 120 words: clear subject line, one-sentence opener stating the ask, 2-3 supporting sentences, specific closing action. Plain professional tone, no filler phrases. Context: <what the email needs to say and to whom>"},
{"q":"resignation letter","d":"email","p":"Write a resignation letter under 150 words: last-day date up top, one sentence of neutral gratitude, an offer to help transition, zero reasons or grievances. Formal but warm. Details: <role, company, last working day>"},
{"q":"cover letter","d":"career","p":"Write a 3-paragraph cover letter under 250 words: hook tying my strongest fact to their top requirement, one paragraph of evidence, brief close. Use only facts I provide — invent nothing. <paste job description> <paste resume or key facts>"},
{"q":"improve my resume","d":"career","p":"Rewrite my resume bullets: for each, return a before/after table with a one-line reason. Strong verb first, outcome over duty, use only stated facts — never invent metrics. Flag 3 gaps I should quantify myself. <paste resume>"},
{"q":"interview prep","d":"career","p":"List the 10 most likely questions for this role, each with a 2-sentence model-answer skeleton (situation then result) I can fill with my own stories, plus the one question I should ask back. <paste job title and company>"},
{"q":"ask for a raise","d":"career","p":"Script the raise conversation: 3 numbered talking points anchored to results I name, one target number with a defensible range, the exact opening sentence, and a 2-line fallback if they say no. Under 200 words total."},
{"q":"write my essay","d":"write","p":"Build the essay scaffold first: thesis in one sentence, 3 body-paragraph topic sentences with the evidence each needs, then a full draft — no padded intro, no 'in conclusion'. Topic and length: <topic and required word count>"},
{"q":"rewrite this professionally","d":"write","p":"Return two rewrites: one polished-formal, one plain-and-direct, each preserving my meaning and roughly my length. Below them, 3 bullets naming what you changed and why. <paste text>"},
{"q":"fix my grammar","d":"write","p":"Return the corrected text first, changes bolded. Then a table of each fix: original, correction, 5-word rule. Preserve my voice and phrasing — grammar and clarity fixes only, no rewrites. <paste text>"},
{"q":"summarize this","d":"summarize","p":"Summarize in exactly 5 bullets: main claim first, then key evidence, then the one number or fact most readers would miss. One sentence per bullet, no bullet restating the title. Add a one-line 'so what'. <paste text>"},
{"q":"explain quantum computing","d":"learn","p":"Explain quantum computing in 3 layers, 2 sentences each: an everyday analogy, how qubits and superposition actually differ from bits, and what it will and won't be good at. End with the most common misconception, corrected."},
{"q":"explain like i'm five","d":"learn","p":"Explain <topic> in 4 short sentences a curious 10-year-old would follow, using one concrete household analogy. Then one sentence on where the analogy breaks. No jargon word without instantly defining it."},
{"q":"7 day japan itinerary","d":"travel","p":"Day-by-day table, 7 rows: city, morning/afternoon/evening one-liners, transit between stops, realistic daily budget in USD. Flag the 3 things to book weeks ahead (trains, teamLab, Ghibli) and the one classic first-timer mistake to skip. Assume a Tokyo-Kyoto core."},
{"q":"3 day paris itinerary","d":"travel","p":"Three-day plan, one line per half-day: sight, nearest metro stop, ideal time slot to dodge queues, and a specific lunch spot nearby. Include per-day budget, the 2 tickets to book ahead (Louvre, Eiffel), and one non-touristy evening."},
{"q":"weekend getaway ideas","d":"travel","p":"Table of 7 getaways within driving distance of <my city>: drive time, best-for (couples, family, solo), signature thing to do, weekend cost for two, and the season it peaks. Rank by value and note which needs booking now."},
{"q":"packing list","d":"travel","p":"Checklist grouped in 5 categories, 25 items max, for <destination, trip length, season>: mark each carry-on or checked, star the 5 items people most often forget, and list 3 things to leave home. Assume one bag."},
{"q":"best time to book flights","d":"travel","p":"Answer in a 3-row table by route type (domestic, international, holiday peak): how many weeks out to book, cheapest departure days, and one fare-alert tactic. Then 3 myths that no longer work (Tuesday trick, incognito), with typical savings ranges."},
{"q":"weekly meal plan","d":"cook","p":"7-day dinner table: dish, 20-word method, prep time, cost per serving. Reuse ingredients across days to cut waste, max 40 minutes any night. Finish with one consolidated grocery list sorted by aisle, plus swaps for picky eaters."},
{"q":"dinner ideas tonight","d":"cook","p":"5 dinners I can start right now, one line each: dish, total time under 30 minutes, the 5 or fewer main ingredients. Order from fastest to most impressive, and mark which need zero shopping from a normal pantry."},
{"q":"recipes with what i have","d":"cook","p":"From my ingredients, give 3 real dishes ranked by fewest extra items needed: name, numbered steps (max 6), cook time, and the one pantry staple that would upgrade it. No recipe requiring a shopping trip. <list your ingredients>"},
{"q":"weight loss plan","d":"health","p":"Build a 4-week plan as a weekly table: daily calorie target from my stats, protein floor in grams, 3 meal templates, step goal, one weigh-in rule. Sustainable 0.5-1% bodyweight per week — no crash tactics. Stats: <age, sex, height, weight, activity>"},
{"q":"how to sleep better","d":"health","p":"Give a 7-item nightly protocol in time order (3 hours pre-bed to lights-out), one sentence each with the mechanism. Then the 3 highest-impact habits ranked by evidence strength, and the one popular tip that backfires."},
{"q":"beginner workout plan","d":"fit","p":"3-day-per-week full-body table: 6 exercises per day with sets x reps, rest, and a 10-word form cue each. Bodyweight and dumbbells only, 45 minutes per session, with a 4-week progression rule and the two signs to deload."},
{"q":"lose belly fat","d":"fit","p":"Start with the truth in 2 sentences: no spot reduction — calorie deficit plus training. Then a 5-point weekly plan (deficit size, protein target, 2 strength days, daily steps, sleep floor), each with a measurable 4-week checkpoint."},
{"q":"business ideas","d":"biz","p":"Table of 7 ideas matched to <my skills and budget>: startup cost, effort level, concrete first step this week, why-now trend, realistic monthly revenue at month 12. No dropshipping clichés; rank by odds of a first paying customer within 60 days."},
{"q":"write a business plan","d":"biz","p":"Produce a one-page plan in 9 headed sections, max 3 sentences each: problem, customer, offer, pricing, channel, competition, unit economics, 90-day milestones, top risk with mitigation. Real numbers over adjectives — flag every assumption to validate. Business: <describe your business>"},
{"q":"side hustle ideas","d":"biz","p":"Table of 8 side hustles: hours per week, startup cost under $500, realistic monthly income by month 3, a first step doable tonight, and why demand is rising now. Match to <skills and free hours>; cut anything needing an audience I don't have."},
{"q":"business name ideas","d":"biz","p":"Generate 15 names in 3 styles (descriptive, invented, evocative), 5 each with a one-line rationale. For the top 3: a check-the-.com note, trademark red flags to search, and how it sounds said aloud. Business: <what it does and the vibe>"},
{"q":"validate my business idea","d":"biz","p":"Stress-test it: 5-row table of riskiest assumptions ranked by kill-probability, each with a sub-$100 test runnable this week and a pass/fail metric. Then the strongest competitor and my honest wedge. Verdict in one sentence. Idea: <describe it>"},
{"q":"instagram caption ideas","d":"market","p":"Write 6 captions: 2 punchy one-liners, 2 story-style under 40 words, 2 question-hooks. Each with 5 niche hashtags, no generic #love. The first line must work before the 'more' fold. Post: <describe the post and brand voice>"},
{"q":"marketing plan","d":"market","p":"One-page plan: target customer in one sentence, one core message, then a 5-row channel table — tactic, weekly hours, cost, KPI, expected 90-day result. Pick 2 channels max to start and name what I'm deliberately ignoring. Business: <product and budget>"},
{"q":"write a python script","d":"code","p":"Deliver one runnable script: stdlib-first, type hints, a docstring stating usage, graceful errors on bad input, and a __main__ example. After the code, 3 bullets: assumptions made, edge cases handled, how to test. Task: <describe what it should do>"},
{"q":"explain this code","d":"code","p":"Explain top-down in 3 passes: one-sentence purpose, numbered walkthrough of the flow (max 8 steps), then gotchas — hidden state, edge cases, complexity. Flag any line doing something non-obvious with a one-line why. <paste code>"},
{"q":"fix this error","d":"debug","p":"Diagnose before prescribing: root cause in 2 sentences, then the minimal fix as a diff, then how to verify in one command. If the cause is ambiguous, give the 2 likeliest with a distinguishing test for each. <paste error and code>"},
{"q":"excel formula help","d":"tech","p":"Give the working formula first with cell references matching my layout, then a numbered plain-English breakdown clause by clause, one common #REF or #N/A pitfall, and the modern alternative (XLOOKUP, FILTER) if mine is legacy. Task: <what the formula should do>"},
{"q":"monthly budget","d":"money","p":"Build a budget table from my numbers: fixed, variable, and savings rows with dollar amounts and percent of take-home, benchmarked against 50/30/20. Name the 2 biggest leaks with a specific monthly recovery figure each. Numbers: <income and main expenses>"},
{"q":"investing for beginners","d":"money","p":"Explain in 5 numbered steps in action order: emergency fund, employer match, tax-advantaged accounts, low-cost index fund, automation. Two sentences each naming the specific account or fund type. End with 3 costly beginner mistakes. Be concrete, skip boilerplate disclaimers."},
{"q":"best laptop 2026","d":"shop","p":"Table of 5 picks by persona (student, creator, coder, gamer, budget): model, price, standout spec, dealbreaker, who should skip it. Declare a best-overall with a two-sentence reason, and name one spec that is overpriced marketing."},
{"q":"gift ideas","d":"shop","p":"10 gift ideas in a table for <person, occasion, budget>: item, price, why it fits them specifically, where to buy. Range from safe to memorable; mark the 2 needing order lead time. No gift cards unless nothing else fits."},
{"q":"iphone vs android","d":"decide","p":"Verdict first: one sentence naming who each suits. Then a 6-row table — camera, ecosystem lock-in, update longevity, customization, price at each tier, switching cost. End with the single question that actually decides it for most people."},
{"q":"pros and cons","d":"decide","p":"Table for <your decision>: max 5 pros and 5 cons, each weighted 1-5 for how much it matters, not just listed. Sum the weights, state the lean, then name the one factor that would flip the answer."},
{"q":"restaurants near me","d":"local","p":"List 5 spots in a table for <your neighborhood or intersection>: cuisine, price tier, signature dish, walk or drive time, why locals rate it. Skip chains, note which need reservations tonight, and add one wildcard pick."},
{"q":"things to do near me","d":"local","p":"8 options within 30 minutes of <your location> in a table: activity, cost, time needed, indoor or outdoor, best hour to go. Include at least 2 free ones and 1 most people don't know. Order by effort, lowest first."},
{"q":"coffee shops near me","d":"local","p":"5 cafés near <your location>, one line each: vibe (laptop-friendly, outlets, noise), signature drink, walk time, weekday vs weekend crowding. Crown a best-for-working and a best-for-conversation winner. No chains."},
{"q":"date ideas near me","d":"local","p":"7 date ideas around <your city> in a table: activity, cost per couple, duration, weather backup, why it sparks conversation. Range from free to splurge, mark the 2 that need booking, and flag first-date-safe versus established-couple picks."},
{"q":"gyms near me","d":"local","p":"Compare 5 gyms near <your location> in a table: monthly price, contract trap or none, peak-hour crowding, standout facility, best-for (lifting, classes, budget). End with the 2 questions to ask on a trial visit before signing anything."},
{"q":"learn spanish","d":"lang","p":"Give a 30-day starter plan at 20 minutes daily, as a 4-week table: weekly focus, daily drill, one free resource each. Include the 50-word survival core to memorize first and the habit that beats every app: daily spoken output."},
{"q":"translate this","d":"lang","p":"Translate into <target language>, natural register over word-for-word. Return the translation, a back-translation so I can check meaning, and footnotes on any phrase where a literal rendering would mislead (max 3). <paste text>"},
{"q":"solve this math problem","d":"math","p":"Show the solution as numbered steps, one operation per step with the rule named (distribute, factor, substitute). Box the final answer, then verify by plugging it back in. Show the fastest method and name one alternative. <paste problem>"},
{"q":"what to text back","d":"social","p":"Give 3 reply options — warm, neutral, boundary-setting — each under 25 words and sounding like a person, not a therapist. One line under each on the response it likely invites. Context: <paste the conversation and what you want>"},
{"q":"apology message","d":"social","p":"Write a 4-sentence apology: name the specific harm, take ownership with zero 'if' or 'but', state the concrete change, ask for nothing in return. Then a shorter text-message version. What happened: <what you did and to whom>"},
{"q":"write a poem","d":"create","p":"Write the poem in 12-16 lines with one governing image sustained throughout, concrete nouns over abstractions, no forced rhyme unless requested. Then 2 sentences naming the central choice made and the one line you'd cut. Subject: <topic, occasion, tone>"},
{"q":"toddler tantrums","d":"parent","p":"Give a 4-step in-the-moment script (exact words, kneel to their level, name the feeling, hold the limit) plus a 3-row prevention table: common trigger, early sign, pre-empt move. Two sentences on what makes tantrums worse: logic and lectures."},
{"q":"cleaning schedule","d":"home","p":"Build a table: daily 10-minute reset of 5 tasks, weekly Mon-Sun rotation of one 20-minute zone per day, monthly deep-clean list of 6. Mark tasks kids can own, and name the one daily habit that halves everything: clear counters nightly."},
{"q":"tell me a joke","d":"fun","p":"Tell 3 jokes in rising order of groan: one clean one-liner, one pun, one setup-punchline under 40 words. No explaining the joke, no chicken-crossing retreads. If one lands flat, it's the pun — it always is."},
{"q":"study schedule","d":"plan","p":"Build a weekly table from now to <exam date and subjects>: day, subject, one 45-minute active-recall block, 10-minute review of prior material. Weight topics by weakness not comfort, keep one full rest day, and end each week with a self-test slot."},
{"q":"review my lease","d":"legal","p":"Scan clause-by-clause and return a table of red flags only: clause, plain-English meaning, risk level, exact question to ask the landlord. Check break fees, auto-renewal, deposit deductions, repair duties, guest limits. Flag anything that needs a real lawyer. <paste lease>"},
{"q":"analyze this data","d":"analyze","p":"Report findings in order of surprise, not column order: 5 bullets max, each with the number that proves it. Then one table of key stats, one caveat about data quality, and the single follow-up metric worth collecting. <paste data>"},
{"q":"generate a logo","d":"image","p":"First, 3 concept directions in a table: symbol idea, style, palette with hex codes, why it fits the brand. Then one detailed image-generation prompt for the strongest concept — flat vector, scalable, legible at 32px. Brand: <name, industry, vibe>"},
{"q":"research this topic","d":"agent","p":"Run deep research on <topic and the decision it informs>: executive summary in 5 bullets, a source table (claim, source, date, confidence), points where credible sources disagree, and what remains unknown. Prioritize primary sources over aggregators; max 10 sources."},
{"q":"set up ci for my repo","d":"agent","p":"Set up CI for <my repo> end to end: plan first, detect the stack, add a workflow running tests and lint on every push, verify it passes, and report what you added. Ask before changing anything outside CI config."},
{"q":"upgrade all my dependencies safely","d":"agent","p":"Upgrade all my dependencies safely: plan the order, bump one group at a time, run the test suite after each change, and roll forward only when green. Ask before any major-version or lockfile-wide change, and finish with a report of what was upgraded, skipped, and why."},
{"q":"migrate my database schema","d":"agent","p":"Migrate the database schema to <target change>: draft a migration plan, write reversible migrations, apply them to a staging copy first, verify data integrity after each step, and report the outcome. Never drop or overwrite data without asking me first."},
{"q":"keep my prs green","d":"agent","p":"Keep my open PRs green: check each one, plan fixes for failing checks and merge conflicts, apply them branch by branch, rerun CI to confirm, and report the status of every PR. Ask before force-pushing, closing, or merging anything."},
{"q":"refactor my codebase","d":"agent","p":"Refactor <the module> without changing behavior: map the current structure, propose a plan, make small verifiable changes with tests passing after each one, and finish with a report of what moved and why. Ask before deleting files or touching public APIs."},
{"q":"build and deploy my website","d":"agent","p":"Build and deploy my website end to end: plan the pipeline, build the site, run checks, deploy to <hosting target>, verify the live URL responds correctly, and report each step's result. Ask before overwriting an existing deployment or changing DNS."}
];
