/* Prompt Studio data — autocomplete vocabulary + one-tap modifiers.
   Generated from a curated sweep of what people actually ask LLMs, plus
   modifier phrasings distilled from public prompt libraries (Anthropic,
   OpenAI, Google guides, awesome-chatgpt-prompts). */

window.PS_MODS = [
 {
  "id": "table",
  "label": "Table",
  "text": "Format as a compact table."
 },
 {
  "id": "bul3",
  "label": "3 bullets",
  "text": "Answer in 3 bullets max."
 },
 {
  "id": "steps",
  "label": "Steps",
  "text": "Numbered steps only, one line each.",
  "doms": [
   "tech",
   "home",
   "cook",
   "plan",
   "debug",
   "fit"
  ]
 },
 {
  "id": "eli5",
  "label": "ELI5",
  "text": "Explain like I'm five, 3 sentences.",
  "doms": [
   "learn",
   "sci",
   "math"
  ]
 },
 {
  "id": "example",
  "label": "Real example",
  "text": "Give one concrete real-world example.",
  "doms": [
   "learn",
   "biz",
   "market",
   "lang"
  ]
 },
 {
  "id": "diagram",
  "label": "Diagram",
  "text": "Include a simple text diagram.",
  "doms": [
   "learn",
   "sci",
   "math",
   "tech",
   "code"
  ]
 },
 {
  "id": "proscons",
  "label": "Pros/cons",
  "text": "3 pros, 3 cons, nothing else.",
  "doms": [
   "decide",
   "shop",
   "biz"
  ]
 },
 {
  "id": "w100",
  "label": "100 words",
  "text": "Under 100 words total."
 },
 {
  "id": "checklist",
  "label": "Checklist",
  "text": "Format as an ordered checklist.",
  "doms": [
   "plan",
   "travel",
   "home",
   "career"
  ]
 },
 {
  "id": "analogy",
  "label": "Analogy",
  "text": "Include one short analogy.",
  "doms": [
   "learn",
   "sci"
  ]
 },
 {
  "id": "quiz",
  "label": "Quiz me",
  "text": "Then quiz me with 3 short questions.",
  "doms": [
   "learn",
   "lang",
   "math",
   "sci"
  ]
 },
 {
  "id": "next",
  "label": "Next step",
  "text": "End with one concrete next step.",
  "doms": [
   "career",
   "biz",
   "plan",
   "money",
   "fit"
  ]
 },
 {
  "id": "yesno",
  "label": "Yes/no",
  "text": "Start with yes or no, then why.",
  "doms": [
   "decide",
   "health",
   "money"
  ]
 },
 {
  "id": "top3",
  "label": "Top 3",
  "text": "Just the top 3, ranked.",
  "doms": [
   "shop",
   "create",
   "fun"
  ]
 },
 {
  "id": "compare",
  "label": "Compare",
  "text": "Compare in a two-column table.",
  "doms": [
   "decide",
   "shop",
   "tech"
  ]
 },
 {
  "id": "mistakes",
  "label": "Mistakes",
  "text": "List the 3 most common mistakes.",
  "doms": [
   "learn",
   "fit",
   "cook",
   "money",
   "career"
  ]
 },
 {
  "id": "numbers",
  "label": "Numbers",
  "text": "Include specific numbers and figures.",
  "doms": [
   "money",
   "biz",
   "analyze",
   "fit",
   "sci"
  ]
 },
 {
  "id": "sources",
  "label": "Sources",
  "text": "Cite 2–3 reputable sources.",
  "doms": [
   "health",
   "sci",
   "money",
   "legal"
  ]
 },
 {
  "id": "template",
  "label": "Template",
  "text": "Give a fill-in-the-blank template.",
  "doms": [
   "write",
   "email",
   "biz",
   "legal"
  ]
 },
 {
  "id": "codeonly",
  "label": "Code only",
  "text": "Code only, no explanation.",
  "doms": [
   "code",
   "debug"
  ]
 },
 {
  "id": "mermaid",
  "label": "Mermaid",
  "text": "Output a mermaid diagram only.",
  "doms": [
   "code",
   "agent",
   "tech"
  ]
 },
 {
  "id": "cheat",
  "label": "Cheat sheet",
  "text": "Format as a one-screen cheat sheet.",
  "doms": [
   "learn",
   "lang",
   "math",
   "code"
  ]
 },
 {
  "id": "counter",
  "label": "Counter",
  "text": "Add one strong counterargument.",
  "doms": [
   "decide",
   "analyze",
   "biz"
  ]
 },
 {
  "id": "askfirst",
  "label": "Ask first",
  "text": "Ask one clarifying question before answering.",
  "doms": [
   "agent",
   "debug",
   "decide",
   "legal"
  ]
 },
 {
  "id": "blunt",
  "label": "Blunt",
  "text": "Be blunt; no hedging or caveats."
 },
 {
  "id": "casual",
  "label": "Casual",
  "text": "Casual, conversational tone.",
  "doms": [
   "write",
   "email",
   "social",
   "fun"
  ]
 },
 {
  "id": "formal",
  "label": "Formal",
  "text": "Formal, professional tone.",
  "doms": [
   "write",
   "email",
   "career",
   "legal"
  ]
 },
 {
  "id": "deeper",
  "label": "Deeper",
  "text": "Go one level deeper, still brief."
 }
];

window.PS_VOCAB = [
{"t":"invest 10k","d":"money"},
{"t":"xbox vs ps5","d":"fun"},
{"t":"ev vs hybrid","d":"decide"},
{"t":"fix my resume","d":"career"},
{"t":"run faster 5k","d":"fit"},
{"t":"fix cors error","d":"debug"},
{"t":"sql join types","d":"code"},
{"t":"open a roth ira","d":"money"},
{"t":"outline a novel","d":"write"},
{"t":"quit sugar plan","d":"health"},
{"t":"stoicism basics","d":"learn"},
{"t":"undo git rebase","d":"code"},
{"t":"couch to 5k plan","d":"fit"},
{"t":"css center a div","d":"code"},
{"t":"date night ideas","d":"fun"},
{"t":"gut health foods","d":"health"},
{"t":"next js vs react","d":"code"},
{"t":"vitamin d dosage","d":"health"},
{"t":"youtube seo tips","d":"market"},
{"t":"chatgpt vs claude","d":"tech"},
{"t":"jump rope workout","d":"fit"},
{"t":"side hustle ideas","d":"biz"},
{"t":"vpn do i need one","d":"tech"},
{"t":"adopt a dog or cat","d":"decide"},
{"t":"apartment vs house","d":"decide"},
{"t":"avoid jet lag tips","d":"travel"},
{"t":"cheap dinner ideas","d":"cook"},
{"t":"duolingo vs babbel","d":"lang"},
{"t":"fix a leaky faucet","d":"home"},
{"t":"haiku about autumn","d":"create"},
{"t":"job interview prep","d":"career"},
{"t":"merge conflict fix","d":"debug"},
{"t":"pitch deck outline","d":"biz"},
{"t":"tiktok video ideas","d":"social"},
{"t":"yoga for back pain","d":"fit"},
{"t":"baby sleep schedule","d":"parent"},
{"t":"bread without yeast","d":"cook"},
{"t":"career change at 40","d":"career"},
{"t":"instagram bio ideas","d":"social"},
{"t":"keto dinner recipes","d":"cook"},
{"t":"math help fractions","d":"math"},
{"t":"nda template simple","d":"legal"},
{"t":"stock vs index fund","d":"money"},
{"t":"toddler won't sleep","d":"parent"},
{"t":"why is the sky blue","d":"sci"},
{"t":"world war 2 summary","d":"learn"},
{"t":"zoloft side effects","d":"health"},
{"t":"zoom interview tips","d":"career"},
{"t":"5 year plan examples","d":"plan"},
{"t":"apy vs interest rate","d":"money"},
{"t":"budget for a wedding","d":"money"},
{"t":"build muscle at home","d":"fit"},
{"t":"crypto for beginners","d":"money"},
{"t":"easy meal prep ideas","d":"cook"},
{"t":"etsy shop name ideas","d":"biz"},
{"t":"git undo last commit","d":"code"},
{"t":"grad school worth it","d":"decide"},
{"t":"heat pump vs furnace","d":"home"},
{"t":"kubernetes vs docker","d":"tech"},
{"t":"learn to type faster","d":"learn"},
{"t":"migraine relief fast","d":"health"},
{"t":"passive income ideas","d":"money"},
{"t":"quick dinner for two","d":"cook"},
{"t":"quiet a squeaky door","d":"home"},
{"t":"riddles with answers","d":"fun"},
{"t":"time blocking method","d":"plan"},
{"t":"tone down this email","d":"write"},
{"t":"trip to japan 7 days","d":"travel"},
{"t":"zero-based budgeting","d":"money"},
{"t":"analyze this csv data","d":"analyze"},
{"t":"ankle sprain recovery","d":"health"},
{"t":"burnout warning signs","d":"health"},
{"t":"carry on packing tips","d":"travel"},
{"t":"clear cache on iphone","d":"tech"},
{"t":"dna vs rna difference","d":"sci"},
{"t":"docker compose basics","d":"tech"},
{"t":"image for blog header","d":"image"},
{"t":"image prompt for logo","d":"image"},
{"t":"logo ideas for bakery","d":"image"},
{"t":"mac vs windows laptop","d":"decide"},
{"t":"mattress buying guide","d":"shop"},
{"t":"morning routine ideas","d":"plan"},
{"t":"nyc weekend itinerary","d":"travel"},
{"t":"online business ideas","d":"biz"},
{"t":"organize small closet","d":"home"},
{"t":"out of office message","d":"email"},
{"t":"overnight oats recipe","d":"cook"},
{"t":"ozempic pros and cons","d":"health"},
{"t":"plan a surprise party","d":"plan"},
{"t":"roast chicken in oven","d":"cook"},
{"t":"sleep better at night","d":"health"},
{"t":"spanish for beginners","d":"lang"},
{"t":"study plan for finals","d":"plan"},
{"t":"wifi extender vs mesh","d":"tech"},
{"t":"xml to json converter","d":"code"},
{"t":"youtube channel ideas","d":"create"},
{"t":"agent to sort my inbox","d":"agent"},
{"t":"analyze survey results","d":"analyze"},
{"t":"anniversary gift ideas","d":"shop"},
{"t":"app crashes on startup","d":"debug"},
{"t":"ask for a raise script","d":"career"},
{"t":"automate email replies","d":"agent"},
{"t":"best exercises for abs","d":"fit"},
{"t":"board games for adults","d":"fun"},
{"t":"business plan template","d":"biz"},
{"t":"compare two job offers","d":"decide"},
{"t":"data cleaning in excel","d":"analyze"},
{"t":"dog won't stop barking","d":"home"},
{"t":"flight deals to europe","d":"travel"},
{"t":"german cases explained","d":"lang"},
{"t":"improve my wifi signal","d":"tech"},
{"t":"japanese for beginners","d":"lang"},
{"t":"kitchen remodel budget","d":"home"},
{"t":"knee pain when running","d":"fit"},
{"t":"knitting for beginners","d":"create"},
{"t":"meal prep for the week","d":"cook"},
{"t":"midjourney prompt tips","d":"image"},
{"t":"negotiate salary offer","d":"career"},
{"t":"rent vs buy calculator","d":"decide"},
{"t":"rest api design basics","d":"code"},
{"t":"restyle photo as anime","d":"image"},
{"t":"sick day email to boss","d":"email"},
{"t":"smart thermostat setup","d":"home"},
{"t":"standing desk worth it","d":"shop"},
{"t":"summarize this article","d":"summarize"},
{"t":"teenager attitude help","d":"parent"},
{"t":"valentine's gift ideas","d":"shop"},
{"t":"vlookup vs index match","d":"tech"},
{"t":"xbox parental controls","d":"parent"},
{"t":"xlsx to csv conversion","d":"tech"},
{"t":"yearly budget template","d":"money"},
{"t":"apology email to client","d":"email"},
{"t":"cold email to investors","d":"email"},
{"t":"conjugate ser and estar","d":"lang"},
{"t":"dating profile bio help","d":"social"},
{"t":"dinner party menu for 8","d":"cook"},
{"t":"dishwasher not draining","d":"home"},
{"t":"emergency fund how much","d":"money"},
{"t":"graduation speech ideas","d":"write"},
{"t":"healthy breakfast ideas","d":"cook"},
{"t":"ideas for team building","d":"biz"},
{"t":"keywords for my website","d":"market"},
{"t":"kids screen time limits","d":"parent"},
{"t":"lose weight without gym","d":"fit"},
{"t":"memory leak in node app","d":"debug"},
{"t":"pandas group by example","d":"code"},
{"t":"podcast episode outline","d":"create"},
{"t":"poem for mom's birthday","d":"create"},
{"t":"security deposit rights","d":"legal"},
{"t":"server 500 error causes","d":"debug"},
{"t":"skills to learn in 2026","d":"career"},
{"t":"sourdough starter guide","d":"cook"},
{"t":"speeding ticket options","d":"legal"},
{"t":"split the bill with tip","d":"math"},
{"t":"summarize meeting notes","d":"summarize"},
{"t":"video editing apps free","d":"create"},
{"t":"x-ray results explained","d":"health"},
{"t":"yard drainage solutions","d":"home"},
{"t":"zapier automation ideas","d":"agent"},
{"t":"air fryer chicken recipe","d":"cook"},
{"t":"best time to visit italy","d":"travel"},
{"t":"climate change key facts","d":"sci"},
{"t":"college essay brainstorm","d":"write"},
{"t":"copyright for my artwork","d":"legal"},
{"t":"enhance old family photo","d":"image"},
{"t":"explain machine learning","d":"learn"},
{"t":"google ads for beginners","d":"market"},
{"t":"grow instagram followers","d":"market"},
{"t":"hangover cure that works","d":"health"},
{"t":"hobbies to try this year","d":"fun"},
{"t":"iphone or android switch","d":"decide"},
{"t":"iron deficiency symptoms","d":"health"},
{"t":"javascript array methods","d":"code"},
{"t":"meditation for beginners","d":"health"},
{"t":"mortgage rates explained","d":"money"},
{"t":"name ideas for a podcast","d":"create"},
{"t":"news summary of the week","d":"summarize"},
{"t":"paint colors for bedroom","d":"home"},
{"t":"pay off credit card debt","d":"money"},
{"t":"photosynthesis explained","d":"sci"},
{"t":"picky eater toddler tips","d":"parent"},
{"t":"potty training in 3 days","d":"parent"},
{"t":"python indentation error","d":"debug"},
{"t":"quarterly goals template","d":"plan"},
{"t":"seo basics for beginners","d":"market"},
{"t":"short story prompt ideas","d":"create"},
{"t":"solve quadratic equation","d":"math"},
{"t":"song lyrics about summer","d":"create"},
{"t":"speed reading techniques","d":"learn"},
{"t":"text back after ghosting","d":"social"},
{"t":"typescript vs javascript","d":"code"},
{"t":"unclog a drain naturally","d":"home"},
{"t":"weekend plans when bored","d":"fun"},
{"t":"weekly schedule template","d":"plan"},
{"t":"wine pairing with salmon","d":"cook"},
{"t":"wordpress vs squarespace","d":"tech"},
{"t":"zero waste swaps at home","d":"home"},
{"t":"algebra word problem help","d":"math"},
{"t":"anxiety coping techniques","d":"health"},
{"t":"automate my daily reports","d":"agent"},
{"t":"backup my photos to cloud","d":"tech"},
{"t":"best time to book flights","d":"travel"},
{"t":"down payment savings plan","d":"money"},
{"t":"excel formula for vlookup","d":"tech"},
{"t":"find trends in sales data","d":"analyze"},
{"t":"french phrases for travel","d":"lang"},
{"t":"gluten free dessert ideas","d":"cook"},
{"t":"grocery list for the week","d":"cook"},
{"t":"jazz albums for beginners","d":"fun"},
{"t":"learn python from scratch","d":"learn"},
{"t":"lease agreement red flags","d":"legal"},
{"t":"linkedin summary examples","d":"career"},
{"t":"notion setup for students","d":"tech"},
{"t":"probability of dice rolls","d":"math"},
{"t":"protein intake calculator","d":"fit"},
{"t":"python list comprehension","d":"code"},
{"t":"react useeffect explained","d":"code"},
{"t":"remove mold from bathroom","d":"home"},
{"t":"retirement savings by age","d":"money"},
{"t":"thesis statement examples","d":"write"},
{"t":"tldr of this email thread","d":"summarize"},
{"t":"travel insurance worth it","d":"travel"},
{"t":"used car buying checklist","d":"shop"},
{"t":"will and testament basics","d":"legal"},
{"t":"write a mission statement","d":"biz"},
{"t":"zodiac sign compatibility","d":"fun"},
{"t":"decline a meeting politely","d":"email"},
{"t":"draft a resignation letter","d":"write"},
{"t":"interview questions to ask","d":"career"},
{"t":"itinerary for paris 3 days","d":"travel"},
{"t":"jealousy in a relationship","d":"social"},
{"t":"llc vs sole proprietorship","d":"biz"},
{"t":"make friends in a new city","d":"social"},
{"t":"privacy policy for website","d":"legal"},
{"t":"quotes for graduation card","d":"write"},
{"t":"regex for email validation","d":"code"},
{"t":"road trip route california","d":"travel"},
{"t":"science fair project ideas","d":"sci"},
{"t":"translate email to spanish","d":"lang"},
{"t":"update my linkedin profile","d":"career"},
{"t":"uti symptoms and treatment","d":"health"},
{"t":"vacation ideas for couples","d":"travel"},
{"t":"work from home setup ideas","d":"home"},
{"t":"workout plan 3 days a week","d":"fit"},
{"t":"yeast substitute in baking","d":"cook"},
{"t":"ai tools for small business","d":"biz"},
{"t":"bash script to rename files","d":"code"},
{"t":"build a chatbot for my site","d":"agent"},
{"t":"caption ideas for instagram","d":"social"},
{"t":"compound interest explained","d":"money"},
{"t":"cover letter for internship","d":"career"},
{"t":"email to reschedule meeting","d":"email"},
{"t":"fantasy football team names","d":"fun"},
{"t":"first time home buyer steps","d":"home"},
{"t":"garden layout for beginners","d":"home"},
{"t":"guitar chords for beginners","d":"learn"},
{"t":"half marathon training plan","d":"fit"},
{"t":"history of the roman empire","d":"learn"},
{"t":"journal prompts for anxiety","d":"health"},
{"t":"key takeaways from this pdf","d":"summarize"},
{"t":"lasagna recipe from scratch","d":"cook"},
{"t":"packing list for beach trip","d":"travel"},
{"t":"percentage increase formula","d":"math"},
{"t":"running shoes for flat feet","d":"shop"},
{"t":"scrape prices from websites","d":"agent"},
{"t":"undefined is not a function","d":"debug"},
{"t":"upper body dumbbell workout","d":"fit"},
{"t":"x axis labels in matplotlib","d":"code"},
{"t":"yellow leaves on houseplant","d":"home"},
{"t":"zucchini recipes for dinner","d":"cook"},
{"t":"black holes explained simply","d":"sci"},
{"t":"blog post about productivity","d":"write"},
{"t":"chess openings for beginners","d":"learn"},
{"t":"creatine benefits and dosage","d":"fit"},
{"t":"daily news digest automation","d":"agent"},
{"t":"debug null pointer exception","d":"debug"},
{"t":"house offer negotiation tips","d":"home"},
{"t":"interpret blood test results","d":"analyze"},
{"t":"make this sound professional","d":"write"},
{"t":"nap schedule for 6 month old","d":"parent"},
{"t":"newborn checklist essentials","d":"parent"},
{"t":"rolling r pronunciation tips","d":"lang"},
{"t":"small bathroom storage ideas","d":"home"},
{"t":"standard deviation explained","d":"math"},
{"t":"birthday party ideas for kids","d":"fun"},
{"t":"bullet points from transcript","d":"summarize"},
{"t":"customer retention strategies","d":"biz"},
{"t":"email subject lines that work","d":"market"},
{"t":"intermittent fasting schedule","d":"health"},
{"t":"remote work productivity tips","d":"career"},
{"t":"salary range for data analyst","d":"career"},
{"t":"sentiment analysis of reviews","d":"analyze"},
{"t":"spot errors in my spreadsheet","d":"analyze"},
{"t":"unit conversion cups to grams","d":"math"},
{"t":"vegetarian high protein meals","d":"cook"},
{"t":"childproof the house checklist","d":"parent"},
{"t":"fever in toddler when to worry","d":"parent"},
{"t":"generate a birthday card image","d":"image"},
{"t":"lower blood pressure naturally","d":"health"},
{"t":"networking email to a stranger","d":"email"},
{"t":"newsletter ideas for customers","d":"market"},
{"t":"nutrition plan for muscle gain","d":"fit"},
{"t":"questions to ask on first date","d":"social"},
{"t":"refinance my mortgage worth it","d":"money"},
{"t":"resume bullet points for sales","d":"career"},
{"t":"rewrite this paragraph clearly","d":"write"},
{"t":"tax deductions for freelancers","d":"money"},
{"t":"thank you note after interview","d":"email"},
{"t":"visa requirements for thailand","d":"travel"},
{"t":"wedding speech for best friend","d":"write"},
{"t":"essay outline on climate change","d":"write"},
{"t":"follow up email after interview","d":"email"},
{"t":"gift for dad who has everything","d":"shop"},
{"t":"hiring first employee checklist","d":"biz"},
{"t":"long distance relationship tips","d":"social"},
{"t":"quiz questions for trivia night","d":"fun"},
{"t":"weekly meal plan family of four","d":"cook"},
{"t":"best noise cancelling headphones","d":"shop"},
{"t":"condense this report to one page","d":"summarize"},
{"t":"invoice template for freelancers","d":"biz"},
{"t":"product photo background removal","d":"image"},
{"t":"small talk conversation starters","d":"social"},
{"t":"watercolor style portrait prompt","d":"image"},
{"t":"character names for fantasy novel","d":"create"},
{"t":"product launch announcement ideas","d":"market"},
{"t":"recursion explained with examples","d":"learn"},
{"t":"onboarding checklist for new hires","d":"biz"},
{"t":"schedule social posts automatically","d":"agent"},
{"t":"stretching routine for desk workers","d":"fit"},
{"t":"movie recommendations like inception","d":"fun"}
];
