/* Regenerate ../data.js from vocab.json + gold.json.
   Run:  node tools/gen-data.js   (from anywhere — paths are resolved here)

   data.js is GENERATED. Edit tools/vocab.json or tools/gold.json and rerun;
   never hand-edit data.js, the next regeneration will overwrite it.

   PS_MODS is deliberately NOT sourced from this directory: the one-tap
   modifier list is lifted verbatim out of the current data.js so regenerating
   the vocabulary can never perturb it. */

const fs = require('fs');
const path = require('path');
const dir = __dirname;
const DATA = path.join(dir, '..', 'data.js');

const vocab = JSON.parse(fs.readFileSync(path.join(dir, 'vocab.json'), 'utf8'));
const gold = JSON.parse(fs.readFileSync(path.join(dir, 'gold.json'), 'utf8'));

/* Domain ids. Source of truth is the DOMAINS table at the top of app.js;
   duplicated here (not imported) so the generator stays dependency-free. */
const DOMS = new Set(['learn', 'code', 'debug', 'write', 'email', 'career', 'health', 'cook',
  'travel', 'money', 'fit', 'home', 'parent', 'shop', 'create', 'biz', 'market', 'legal',
  'lang', 'math', 'sci', 'plan', 'social', 'fun', 'tech', 'decide', 'summarize', 'analyze',
  'image', 'agent', 'local', 'general']);

/* An entry is what a real person types: lowercase, no sentence punctuation,
   apostrophes and hyphens allowed because "won't" and "x-ray" are how people write. */
const ENTRY_OK = /^[a-z0-9][a-z0-9 '\-&]*[a-z0-9]$/;
const MAX_GOLD_WORDS = 60;
/* Banned openers: the whole thesis is stating what is wanted, not casting a role. */
const ROLEPLAY = /\b(you are (an?|the) |act as|pretend (to be|you)|imagine you are|as an? (expert|professional|world.class))/i;

const fail = msg => { throw new Error(msg); };

/* ---------- vocabulary ---------- */
const seen = new Set();
for (const e of vocab) {
  if (!e || typeof e.t !== 'string' || typeof e.d !== 'string') fail('bad vocab entry: ' + JSON.stringify(e));
  if (!DOMS.has(e.d)) fail(`unknown domain "${e.d}" on vocab entry: ${e.t}`);
  if (e.t !== e.t.trim()) fail('untrimmed vocab entry: ' + JSON.stringify(e.t));
  if (e.t !== e.t.toLowerCase()) fail('vocab entry must be lowercase: ' + e.t);
  if (!ENTRY_OK.test(e.t)) fail('stray punctuation in vocab entry: ' + e.t);
  const w = e.t.split(/\s+/).length;
  if (w < 2 || w > 8) fail(`vocab entry should be 2-8 words (got ${w}): ${e.t}`);
  if (e.t.length > 44) fail(`vocab entry too long (${e.t.length} chars): ${e.t}`);
  if (seen.has(e.t)) fail('duplicate vocab entry: ' + e.t);
  seen.add(e.t);
}
/* The promise is "type one letter, get something useful" — so every letter must land. */
const firsts = new Set(vocab.map(e => e.t[0]));
const missing = 'abcdefghijklmnopqrstuvwxyz'.split('').filter(c => !firsts.has(c));
if (missing.length) fail('no vocabulary entry starts with: ' + missing.join(', '));

/* ---------- gold prompts ---------- */
const qs = new Set();
const ps = new Set();
for (const g of gold) {
  if (!g.q || !g.p || !DOMS.has(g.d)) fail('bad gold entry: ' + JSON.stringify(g));
  if (qs.has(g.q)) fail('duplicate gold q: ' + g.q);
  qs.add(g.q);
  if (ps.has(g.p)) fail('duplicate gold prompt on: ' + g.q);
  ps.add(g.p);
  if (g.q !== g.q.trim().toLowerCase()) fail('gold q must be lowercase and trimmed: ' + g.q);
  const w = g.p.split(/\s+/).length;
  if (w > MAX_GOLD_WORDS) fail(`gold prompt too long (${w}w): ${g.q}`);
  if (ROLEPLAY.test(g.p)) fail('gold prompt uses a role-play opener: ' + g.q);
  if (/go deeper|reply with a number|numbered (ways|follow)/i.test(g.p))
    fail('gold prompt contains drill line (host adds it): ' + g.q);
}

/* ---------- floors: a later edit that shrinks the corpus should be loud ---------- */
if (vocab.length < 850) fail(`vocabulary shrank to ${vocab.length} (floor 850)`);
if (gold.length < 110) fail(`gold cache shrank to ${gold.length} (floor 110)`);

/* ---------- emit ---------- */
/* Shortest first: the autocomplete list reads better when the tersest phrasing
   of an ask is what a one-letter query surfaces. */
vocab.sort((a, b) => a.t.length - b.t.length || a.t.localeCompare(b.t));

const cur = fs.readFileSync(DATA, 'utf8');
const modsMatch = cur.match(/window\.PS_MODS = ([\s\S]*?);\n\n/);
if (!modsMatch) fail('PS_MODS block not found in current data.js');

const out = '/* Prompt Studio data — autocomplete vocabulary, one-tap modifiers, and a\n' +
  '   hand-tuned gold cache of the top real-world LLM queries (researched across\n' +
  '   ChatGPT/Gemini/Claude/Perplexity usage patterns; each prompt pre-reasoned\n' +
  '   for succinct output and served instantly on similarity match).\n\n' +
  '   GENERATED by tools/gen-data.js from tools/vocab.json + tools/gold.json.\n' +
  '   Do not hand-edit — edit those and rerun. */\n\n' +
  'window.PS_MODS = ' + modsMatch[1] + ';\n\n' +
  'window.PS_VOCAB = [\n' + vocab.map(e => JSON.stringify(e)).join(',\n') + '\n];\n\n' +
  'window.PS_GOLD = [\n' + gold.map(e => JSON.stringify(e)).join(',\n') + '\n];\n';

fs.writeFileSync(DATA, out);
console.log('data.js written:', vocab.length, 'vocab,', gold.length, 'gold prompts');
